vim.api.nvim_create_user_command("ToggleMark", function() require("track").toggle() end, {})
vim.api.nvim_create_user_command("RemoveAllMarks", function() require("track").remove() end, {})
vim.api.nvim_create_user_command("JumpToNextMark", function() require("track").jump_to_next() end, {})
vim.api.nvim_create_user_command("JumpToPrevMark", function() require("track").jump_to_prev() end, {})
vim.api.nvim_create_user_command("EditMark", function() require("track").edit() end, {})
vim.api.nvim_create_user_command("SearchMarks", function() require("track").search() end, {})

vim.keymap.set("n", "mm", "<cmd>ToggleMark<CR>", { desc = "Mark toggle" })
vim.keymap.set("n", "mc", "<cmd>RemoveAllMarks<CR>", { desc = "Mark remove all" })
vim.keymap.set("n", "mj", "<cmd>JumpToNextMark<CR>", { desc = "Mark jump to next" })
vim.keymap.set("n", "mn", "<cmd>JumpToNextMark<CR>", { desc = "Mark jump to next" })
vim.keymap.set("n", "mk", "<cmd>JumpToPrevMark<CR>", { desc = "Mark jump to prev" })
vim.keymap.set("n", "mp", "<cmd>JumpToPrevMark<CR>", { desc = "Mark jump to prev" })
vim.keymap.set("n", "me", "<cmd>EditMark<CR>", { desc = "Mark edit" })
vim.keymap.set("n", "ms", "<cmd>SearchMarks<CR>", { desc = "Mark search" })
